# Generated by Django 4.1.1 on 2022-09-25 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.CharField(max_length=200)),
                ('aftor_belgisi', models.CharField(max_length=200)),
                ('invertor_nomeri', models.CharField(max_length=200)),
                ('mualiflar', models.CharField(max_length=200)),
                ('kitob_nomi', models.CharField(max_length=200)),
                ('nashriyot', models.CharField(max_length=200)),
                ('nashr_yili', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('kitob_narxi', models.CharField(max_length=200)),
                ('tili', models.CharField(choices=[('uz', 'uzbekcha'), ('ru', 'ruscha'), ('eng', 'ingilizcha'), ('boshqa', 'boshqa')], max_length=200)),
                ('alfabit', models.CharField(choices=[('lotin', 'lotin'), ('kiril', 'kiril'), ('boshqa', 'boshqa')], max_length=200)),
                ('darslik_turi', models.CharField(choices=[('darslik', 'darslik'), ('o`quv qo`llanma', 'o`quv qo`llanma'), ('uslubiy qo`llanma', 'uslubiy qo`llanma'), ('badiiy', 'badiiy'), ('siyosiy', 'siyosiy'), ('ilmiy', 'ilmiy'), ('lug`at', 'lug`at'), ('managrafiya', 'managrafiya')], max_length=200)),
                ('kitobni_fondagi_soni', models.CharField(max_length=200)),
                ('anatatsiya', models.CharField(max_length=600)),
                ('mundarija', models.CharField(max_length=600)),
                ('kitob_turi', models.CharField(choices=[('kitob', 'kitob'), ('elektron', 'elektron')], max_length=100)),
                ('fayl', models.FileField(blank=True, upload_to='kitob/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
