# Generated by Django 4.1.1 on 2022-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=200)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
