# Generated by Django 4.1.1 on 2022-09-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0002_alter_talaba_tel_raqami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='familya',
            field=models.CharField(max_length=200, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='ism',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='sharifi',
            field=models.CharField(max_length=200, verbose_name='Sharif'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='tel_raqami',
            field=models.CharField(max_length=13),
        ),
    ]
