# Generated by Django 4.1.1 on 2022-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0003_alter_talaba_familya_alter_talaba_ism_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='pasport_raqami',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='pasport_seryasi',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='tel_raqami',
            field=models.CharField(max_length=13, verbose_name='Telefon raqam'),
        ),
    ]
