# Generated by Django 4.1.1 on 2022-09-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharif', '0001_initial'),
        ('familiya', '0001_initial'),
        ('ism', '0002_ism_delete_surname'),
        ('talaba', '0005_alter_talaba_pasport_raqami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='familya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familiya.familiya'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='ism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ism.ism'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='sharifi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharif.sharif'),
        ),
    ]
