# Generated by Django 4.1.1 on 2022-09-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0006_alter_talaba_familya_alter_talaba_ism_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talaba',
            old_name='familya',
            new_name='familiya',
        ),
        migrations.RenameField(
            model_name='talaba',
            old_name='sharifi',
            new_name='sharif',
        ),
    ]
