# Generated by Django 4.1.2 on 2022-10-13 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya_arm', models.CharField(max_length=200, verbose_name='Familiya')),
                ('ism', models.CharField(max_length=200, verbose_name='Ism')),
                ('arm_bolim', models.CharField(choices=[('arm-1', 'arm-1'), ('arm-2', 'arm-2'), ('arm-3', 'arm-3'), ('arm-4', 'arm-4')], max_length=100, verbose_name='ARM bo`lim')),
                ('viloyat', models.CharField(max_length=200, verbose_name='Viloyat')),
                ('shahar_tuman', models.CharField(max_length=200, verbose_name='Shahar tuman')),
                ('kocha', models.CharField(max_length=200, verbose_name='Ko`cha nomi')),
                ('uy_nomeri', models.CharField(max_length=200, verbose_name='Uy nomer')),
                ('lavozimi', models.CharField(choices=[('lavozim', 'lavozim')], max_length=200, verbose_name='Lavozim')),
                ('tel_nomer', models.CharField(max_length=200, verbose_name='Telefon raqam')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
