# Generated by Django 4.1.1 on 2022-09-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm_2', '0003_arm_2_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arm_2',
            name='author',
        ),
    ]
