# Generated by Django 4.1.1 on 2022-10-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm_2', '0006_talaba_kitob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talaba_kitob',
            name='sana',
        ),
    ]
