# Generated by Django 4.1.1 on 2022-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm_2', '0007_remove_talaba_kitob_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba_kitob',
            name='kitob',
            field=models.CharField(max_length=200),
        ),
    ]
