# Generated by Django 4.1.2 on 2022-10-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_arm', '0002_alter_armadmin_lavozimi'),
        ('arm_1', '0002_alter_arm_1_kitob_rasmini_kiriting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm_1',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_arm.armadmin'),
        ),
    ]
