# Generated by Django 4.1.1 on 2022-09-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foydalanuvchi',
            old_name='familya',
            new_name='familiya_a',
        ),
        migrations.RenameField(
            model_name='foydalanuvchi',
            old_name='ism',
            new_name='ism_a',
        ),
        migrations.RenameField(
            model_name='foydalanuvchi',
            old_name='viloyat',
            new_name='viloyat_a',
        ),
    ]
