# Generated by Django 4.1.1 on 2022-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_familya_foydalanuvchi_familiya_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='arm_bolim',
            field=models.CharField(blank=True, choices=[('arm_1', 'arm_1'), ('arm_2', 'arm_2'), ('arm_3', 'arm_3'), ('arm_4', 'arm_4')], max_length=100, verbose_name='ARM bo`lim'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='familiya_a',
            field=models.CharField(max_length=200, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='ism_a',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='kocha',
            field=models.CharField(max_length=200, verbose_name='Ko`cha nomi'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='lavozimi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='shahar_tuman',
            field=models.CharField(max_length=200, verbose_name='Shahar tuman'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='tel_nomer',
            field=models.CharField(max_length=200, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='uy_nomeri',
            field=models.CharField(max_length=200, verbose_name='Uy nomer'),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='viloyat_a',
            field=models.CharField(max_length=200, verbose_name='Viloyat'),
        ),
    ]
