# Generated by Django 4.1.1 on 2022-10-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitob', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitob',
            name='sana',
        ),
    ]
